project:
  type: website
  output-dir: docs/

website:
  title: "Statistical Methods for Neuroimaging"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lecture Notes
        menu:
        - text: "Data Modalities"
          href: 1introduction_data_modalities/introduction_data_modalities.html
          target: "_blank"
        - text: "Preprocessing"
          href: 2preprocessing/preprocessing.html
          target: "_blank"
        - text: "First-level Analysis"
          href: 3first-level_analysis/first-level_analysis.html
          target: "_blank"
        - text: "Group-level Analysis"
          href: 3group-level_analysis/group-level_analysis.html
          target: "_blank"
        - text: "Modern Topics"
          href: 4modern_topics/modern_topics.html
          target: "_blank"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



