---
title: "Homework: *Despicable Me* Preprocessing"
editor: visual
format:
  html:
    toc: true
    standalone: true
    code-fold: true
---

## Overview

**Goal:** *Effectively* implement fMRI preprocessing for the *Despicable Me* data for a single participant. "Effectively" means choosing reasonable parameters, checking the output from each step, and modifying the approach as needed to get good output.

**Instructions:** There are 100 participant folders in the `data/RBC/HBN_BIDS/` [folder](https://vanderbilt.box.com/s/7tb7738agklrsp3sw7d1w7c36g0bn091). One is assigned to you in this [Google doc](https://docs.google.com/document/d/1hYff8xvkZmRjfio6mS5hIENpfoW19KzafYFAcMh5DV4/edit?usp=sharing) where we will put the quality assurance (QA) summaries.

**Deliverables:** This document edited to include

-   Commented code describing each step.
-   Visualizations and commentary, as requested specifically, below.
-   All the output from your preprocessing steps included in the participant's folder on the Box drive.
-   QA summaries generated by FSL in the [Google doc](https://docs.google.com/document/d/1hYff8xvkZmRjfio6mS5hIENpfoW19KzafYFAcMh5DV4/edit?usp=sharing).

**Hint:** This file is located at `2preprocessing/homework/fMRIpreprocessing/fMRIpreprocessing.qmd`.

## Brain extraction (12 pts)

For fMRI preprocessing, FSL requires a brain extracted anatomical T1 image. It needs to be with the same name in the same folder as the T1, with the suffix `<T1 name>_brain.nii.gz`.

1.  Use FSL's tool to bias correct and then brain extract the T1. If you do not apply bias correction, the brain extraction might look bad.
2.  FSL's tool for brain extraction actually doesn't work too well oftentimes. Create another brain extracted image using the following steps:
    -   Linearly register the participants T1 with skull to the MNI 1mm template with skull and save out the transformation matrix.
    -   Invert the transformation matrix.
    -   Register the MNI brain mask to the participant's T1 image using nearest neighbor interpolation.
    -   Mask the participant's T1 with the registered brain mask.
3.  Include a screenshot in this document of both methods of the brain extracted image overlaid in semitransparent color or with a boundary on the unextracted (with skull) T1. Use 1-3 sentences to describe why you prefer one method or another.
4.  For the method that works better, name that file `<T1 name>_brain.nii.gz` in the `anat` folder to be used for fMRI preprocessing.
5.  Save all other output in the folder with the T1 image.

## fMRI preprocessing (12 pts)

Start the FSL GUI from the command line by typing `fsl` and then open the FEAT fMRI Analysis. Set it up to perform preprocessing. If you hover over the options, there is a description that will help you make decisions about the preprocessing parameters throughout.

**Hint:** On my laptop, when I change the tab in the FEAT GUI, all the buttons disappear; if you adjust the window size, they reappear.

**Use these parameters** (other parameter settings you will decide for yourself).

-   Set the output directory to be the folder where the 4D Nifti image is located for that participant.
-   Set it to delete 6 volumes.
-   Use BBR for "Main structural image" registration.
-   Turn on FNIRT for "Standard space" registration and leave the Warp resolution at the default setting.
-   Leave B0 unwarping off.

### Slice timing (6 pts)

The slice timing information for the fMRI data are included in the `.json` file of the same name as the Nifti image in the `func` folder. Create a slice timing text file to use as input for FSL preprocessing.

### Temporal filtering (6 pts)

The stimulus time series we will use is in the first level model in the `data/RBC/stimulusTimeSeries/despicableMe/stickFile.txt` file. Choose an appropriate temporal filtering value in FSL based on the stimuli durations.

Explain here in 1-2 sentences how you decided on your temporal filtering settings.

## Deliverables (9 pts)

-   Place the fMRI to template registration in the [Google doc](https://docs.google.com/document/d/1hYff8xvkZmRjfio6mS5hIENpfoW19KzafYFAcMh5DV4/edit?usp=sharing) under the "Registration QA" section annotated with the subject ID.
-   Place the motion time series image in the [Google doc](https://docs.google.com/document/d/1hYff8xvkZmRjfio6mS5hIENpfoW19KzafYFAcMh5DV4/edit?usp=sharing) under the "Motion correction QA" section annotated with the subject ID.
-   All your output, including intermediate steps like the brain extraction intermediate files, should be in the subject's directories in Box.
